---

- name: Fail if required Woodpecker CI server settings not defined
  ansible.builtin.fail:
    msg: >-
      You need to define a required configuration setting (`{{ item }}`) for using this role.
  when: "vars[item] == ''"
  with_items:
    - devture_woodpecker_ci_server_uid
    - devture_woodpecker_ci_server_gid
    - devture_woodpecker_ci_server_server_fqn
    - devture_woodpecker_ci_server_config_agent_secret
    - devture_woodpecker_ci_server_provider

- name: Fail if required Woodpecker CI server + Gitea settings not defined
  ansible.builtin.fail:
    msg: >-
      You need to define a required configuration setting (`{{ item }}`) for using this role.
  when: "devture_woodpecker_ci_server_provider == 'gitea' and vars[item] == ''"
  with_items:
    - devture_woodpecker_ci_server_config_gitea_url
    - devture_woodpecker_ci_server_config_gitea_client
    - devture_woodpecker_ci_server_config_gitea_secret

- name: Fail if required Woodpecker CI server Traefik integration settings not defined
  ansible.builtin.fail:
    msg: >-
      You need to define a required configuration setting (`{{ item }}`) for using this role.
  when: "devture_woodpecker_ci_server_container_labels_traefik_enabled and vars[item] == ''"
  with_items:
    - devture_woodpecker_ci_server_container_labels_traefik_docker_network
